title: Max Grice, BS, MS # your name (or website title) here
logo: "/images/headshot3.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist / Junior Developer
  <br><br>
  An aspiring biomedical informatician with a passion for precision, functional, and lifestyle medicine. Though my background was originally in computer science, Iâ€™ve always been drawn to how technology can be creatively applied to fit a range of unmet needs, particularly within the healthcare domain. As a recent masters graduate from UT Houstons School of Biomedical Informatics, I am eager to apply myself to whatever challenge I am tasked with solving, learning from failures and successes alike.
  <br><br>
  <a href="linkedin.com/in/max-grice-15885b191">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
